# Generated by Django 2.2.6 on 2019-10-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191027_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='added_on',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
