# Generated by Django 2.2.6 on 2019-10-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191028_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='added_on',
        ),
        migrations.AddField(
            model_name='album',
            name='added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
