# Generated by Django 2.2.6 on 2019-11-02 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191102_2222'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table=None,
        ),
        migrations.AlterModelTable(
            name='artist',
            table=None,
        ),
        migrations.AlterModelTable(
            name='favorite',
            table=None,
        ),
        migrations.AlterModelTable(
            name='playlist',
            table=None,
        ),
        migrations.AlterModelTable(
            name='song',
            table=None,
        ),
    ]
