# Generated by Django 2.2.6 on 2019-11-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191103_0000'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='Album',
        ),
        migrations.AlterModelTable(
            name='artist',
            table='Artist',
        ),
        migrations.AlterModelTable(
            name='favorite',
            table='Favorites',
        ),
        migrations.AlterModelTable(
            name='playlist',
            table='Playlist',
        ),
        migrations.AlterModelTable(
            name='song',
            table='Song',
        ),
    ]
