# Generated by Django 2.2.6 on 2019-11-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191103_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
