# Generated by Django 2.2.6 on 2019-11-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191126_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='followers',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
