# Generated by Django 2.2.6 on 2019-11-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20191126_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='followers',
        ),
    ]
