# Generated by Django 2.2.6 on 2019-11-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_artist_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='no_of_plays',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
