# Generated by Django 2.2.6 on 2019-11-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20191126_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistsong',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='playlistsong',
            name='song',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='PlaylistSong',
        ),
    ]
