# Generated by Django 2.2.6 on 2019-12-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20191128_2142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite_Album',
        ),
    ]
